### ISSUE TITLE
Rssi value is always returning value of 250 

### ISSUE THREAD

**Issue by jyotirajsharma** [DBeath/rssi-aggregator#1]
Hi,

I am using following code :
Xbee Router is configured in AT mode and Xbee coordinator is configured in Coordinator API mode.

**Problem 1:** 
- The condition if (xbee.getResponse().getApiId() == RX_16_RESPONSE) never gets true and goes to else case always and returns RSSI value of 250 and never gets changes even when moving xbee router/coordinator from each other. Please help to fix this asap.

//Receiver side
#include <XBee.h>

XBee xbee = XBee();

Rx16Response rx16 = Rx16Response();
Rx64Response rx64 = Rx64Response();
void setup()
{
     Serial.begin(9600);
    xbee.setSerial(Serial);
}

void loop()
{
    xbee.readPacket(10);
    if (xbee.getResponse().isAvailable())
    {
        if (xbee.getResponse().getApiId() == RX_16_RESPONSE)
        {
            xbee.getResponse().getRx16Response(rx16);
            Serial.print( rx16.getRssi() );
        }
        else
        {
        xbee.getResponse().getRx64Response(rx64);
        Serial.println("inside 64-bit");
        Serial.print( rx16.getRssi() );
        }
        
    }
}
//Transmitter side
#include <XBee.h>

XBee xbee = XBee();

uint8_t payload[] = { 43, 34 };

XBeeAddress64 addr64 = XBeeAddress64(0x0013a200, 0x40BD3A94);

Tx16Request tx16 = Tx16Request(addr64, payload, sizeof(payload));

void setup()
{
     Serial.begin(9600);
    xbee.setSerial(Serial);
}

void loop()
{
    xbee.send( tx16 );
    delay(1000);
}

**Comment by DBeath** [comment]
I'm not sure why it's not recognising the Rx16 response and dropping into your *else* statement. It might be something to do with the settings on your XBees.

You won't be getting the RSSI data from that *else* statement though, because you're reading the Rx16 Reponse, not the Rx64 Response there.

It should be:
```
xbee.getResponse().getRx64Response(rx64);
Serial.println("inside 64-bit");
Serial.print( rx64.getRssi() );
```

**Comment by jyotirajsharma** [comment]
That was just typo. I am reading rx64 only. I think I am getting inside 64-bit because I am using Series 2 Xbees.  But it is reading value 151 from "Serial.print( rx64.getRssi() )" even though I move Tx Xbee few meters away. Any idea why ?

**Comment by DBeath** [comment]
Ok, your problem is that you're using the Series 2 XBees. They don't send RSSI data in the packet, so you can't read it using API commands, because they operate in a Mesh network. You can use the DB commands to read the RSSI of the last packet from the last hop with Series 2. I can't help you any more than that, because I haven't worked with these for years now.
